name: Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Drop org
      run: docker run openconceptlab/oclapi2:qa --rm -v $(pwd):/fhir api python tools/import.py -f /fhir -t https://fhir.qa.openconceptlab.org/orgs/fhir_imports -s ${{ secrets.OCLAPI_TOKEN }} -c https://api.qa.openconceptlab.org/orgs/fhir_imports
