name: Import

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

jobs:
  staging-clear:
    name: Clear on staging
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Clear fhir_imports org
      run: docker run --rm openconceptlab/oclapi2:qa python tools/import.py -t https://fhir.staging.openconceptlab.org/orgs/fhir_imports -s ${{ secrets.OCLAPI_TOKEN }} -c https://api.staging.openconceptlab.org/orgs/fhir_imports
  
  staging-import:
    needs: [staging-clear]
    name: Import on staging
    runs-on: ubuntu-latest
    environment: staging-import

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Import into fhir_imports org
      run: docker run --rm -v $(pwd):/fhir openconceptlab/oclapi2:qa python tools/import.py -f /fhir/All-non-THO-content_all-copies_can-delete -t https://fhir.staging.openconceptlab.org/orgs/fhir_imports -s ${{ secrets.OCLAPI_TOKEN }} -c https://api.staging.openconceptlab.org/orgs/fhir_imports
 
