name: Import

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

jobs:
  qa-clear:
    name: Clear on QA
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Clear fhir_imports org
      run: docker run --rm openconceptlab/oclapi2:qa python tools/import.py -t https://fhir.qa.openconceptlab.org/orgs/fhir_imports -s ${{ secrets.OCLAPI_TOKEN }} -c https://api.qa.openconceptlab.org/orgs/fhir_imports
  
  qa-import:
    needs: [qa-clear]
    name: Import on QA
    runs-on: ubuntu-latest
    environment: qa-import

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Import into fhir_imports org
      run: docker run --rm -v $(pwd):/fhir openconceptlab/oclapi2:qa python tools/import.py -f /fhir/HL7-Terminology-THO/CodeSystem/HL7-CodeSystems-25July2023 -t https://fhir.qa.openconceptlab.org/orgs/fhir_imports -s ${{ secrets.OCLAPI_TOKEN }} -c https://api.qa.openconceptlab.org/orgs/fhir_imports
 
